# --- Basic site info ---
title: " "
email: "andr.ferrara1@gmail.com"
description: "Researcher in macroeconomics and monetary policy"
url: "https://AndreaFerrara1997.github.io"

# Skin and theme options used by AcademicPages (inherits from Minimal Mistakes)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Author info used in sidebar
author:
  name: "Andrea Ferrara"
  avatar: "/images/bio_photo.jpg"
  email: "andr.ferrara1@gmail.com"

  # Build: include _pages so /publications/ works
include:
  - _pages

# Collections that AcademicPages expects
collections:
  publications:
    output: true
  cv:
    output: true

# Plugins typically used by AcademicPages
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink: /:categories/:title/
