# --- Basic site info ---
title: "Andrea Ferrara"
email: "you@example.com"
description: "Researcher in macroeconomics and monetary policy"
url: "https://YOUR_USERNAME.github.io"

# Skin and theme options used by AcademicPages (inherits from Minimal Mistakes)
minimal_mistakes_skin: "default"

# Author info used in sidebar
author:
  name: "Andrea Ferrara"
  avatar: "/images/profile.jpg"
  bio: "Economist. Macro/monetary policy, DSGE, Bayesian estimation."
  location: "Italy"
  email: "you@example.com"
  googlescholar: ""
  orcid: ""
  github: "YOUR_USERNAME"
  linkedin: ""

# Collections that AcademicPages expects
collections:
  posts:
    output: true
  teaching:
    output: true
  publications:
    output: true
  portfolio:
    output: true
  talks:
    output: true

# Plugins typically used by AcademicPages
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink: /:categories/:title/
