# --- Basic site info ---
title: "Andrea Ferrara"
email: "andr.ferrara1@gmail.com"
description: "Researcher in macroeconomics and monetary policy"
url: "https://AndreaFerrara1997.github.io"

# Skin and theme options used by AcademicPages (inherits from Minimal Mistakes)
minimal_mistakes_skin: "default"

# Author info used in sidebar
author:
  name: "Andrea Ferrara"
  avatar: "/images/profile.jpg"
  bio: "."
  location: "Italy"
  email: "andr.ferrara1@gmail.com"
  googlescholar: ""
  orcid: ""
  github: "AndreaFerrara1997"
  linkedin: ""

# Collections that AcademicPages expects
collections:
  posts:
    output: false
  teaching:
    output: false
  publications:
    output: true
  cv:
    output: true
  talks:
    output: false

# Plugins typically used by AcademicPages
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink: /:categories/:title/
